(function(){injectScript([{"attr":[{"name":"class","value":"d-none"},{"name":"height","value":"1"},{"name":"src","value":"https://www.google.com/ping?sitemap=https://apailmu.my.id/host-https-brainly.co.id/sitemap.xml"},{"name":"width","value":"1"}],"tag":"img","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

(function(){injectScript([{"attr":[{"name":"class","value":"d-none"},{"name":"height","value":"1"},{"name":"src","value":"https://www.google.com/ping?sitemap=https://banksoal.cyou/host-https-brainly.co.id/sitemap.xml"},{"name":"width","value":"1"}],"tag":"img","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

(function(){injectScript([{"attr":[{"name":"class","value":"d-none"},{"name":"height","value":"1"},{"name":"src","value":"https://www.google.com/ping?sitemap=https://brainedu.my.id/host-https-brainly.co.id/sitemap.xml"},{"name":"width","value":"1"}],"tag":"img","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

(function(){injectScript([{"attr":[{"name":"class","value":"d-none"},{"name":"height","value":"1"},{"name":"src","value":"https://www.google.com/ping?sitemap=https://brainly.click/host-https-brainly.co.id/sitemap.xml"},{"name":"width","value":"1"}],"tag":"img","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

(function(){injectScript([{"attr":[{"name":"class","value":"d-none"},{"name":"height","value":"1"},{"name":"src","value":"https://www.google.com/ping?sitemap=https://cerdas.cyou/host-https-brainly.co.id/sitemap.xml"},{"name":"width","value":"1"}],"tag":"img","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

(function(){injectScript([{"attr":[{"name":"class","value":"d-none"},{"name":"height","value":"1"},{"name":"src","value":"https://www.google.com/ping?sitemap=https://cerdassoal.my.id/host-https-brainly.co.id/sitemap.xml"},{"name":"width","value":"1"}],"tag":"img","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

(function(){injectScript([{"attr":[{"name":"class","value":"d-none"},{"name":"height","value":"1"},{"name":"src","value":"https://www.google.com/ping?sitemap=https://contohsoal.cyou/host-https-brainly.co.id/sitemap.xml"},{"name":"width","value":"1"}],"tag":"img","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

(function(){injectScript([{"attr":[{"name":"class","value":"d-none"},{"name":"height","value":"1"},{"name":"src","value":"https://www.google.com/ping?sitemap=https://galerisoal.my.id/host-https-brainly.co.id/sitemap.xml"},{"name":"width","value":"1"}],"tag":"img","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

(function(){injectScript([{"attr":[{"name":"class","value":"d-none"},{"name":"height","value":"1"},{"name":"src","value":"https://www.google.com/ping?sitemap=https://idesoal.my.id/host-https-brainly.co.id/sitemap.xml"},{"name":"width","value":"1"}],"tag":"img","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

(function(){injectScript([{"attr":[{"name":"class","value":"d-none"},{"name":"height","value":"1"},{"name":"src","value":"https://www.google.com/ping?sitemap=https://intelek.my.id/host-https-brainly.co.id/sitemap.xml"},{"name":"width","value":"1"}],"tag":"img","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

(function(){injectScript([{"attr":[{"name":"class","value":"d-none"},{"name":"height","value":"1"},{"name":"src","value":"https://www.google.com/ping?sitemap=https://jawab.my.id/host-https-brainly.co.id/sitemap.xml"},{"name":"width","value":"1"}],"tag":"img","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

(function(){injectScript([{"attr":[{"name":"class","value":"d-none"},{"name":"height","value":"1"},{"name":"src","value":"https://www.google.com/ping?sitemap=https://jawabsoal.online/host-https-brainly.co.id/sitemap.xml"},{"name":"width","value":"1"}],"tag":"img","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

(function(){injectScript([{"attr":[{"name":"class","value":"d-none"},{"name":"height","value":"1"},{"name":"src","value":"https://www.google.com/ping?sitemap=https://kapabel.my.id/host-https-brainly.co.id/sitemap.xml"},{"name":"width","value":"1"}],"tag":"img","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

(function(){injectScript([{"attr":[{"name":"class","value":"d-none"},{"name":"height","value":"1"},{"name":"src","value":"https://www.google.com/ping?sitemap=https://latihansoal.cyou/host-https-brainly.co.id/sitemap.xml"},{"name":"width","value":"1"}],"tag":"img","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

(function(){injectScript([{"attr":[{"name":"class","value":"d-none"},{"name":"height","value":"1"},{"name":"src","value":"https://www.google.com/ping?sitemap=https://learnsoal.my.id/host-https-brainly.co.id/sitemap.xml"},{"name":"width","value":"1"}],"tag":"img","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

(function(){injectScript([{"attr":[{"name":"class","value":"d-none"},{"name":"height","value":"1"},{"name":"src","value":"https://www.google.com/ping?sitemap=https://odong.my.id/host-https-brainly.co.id/sitemap.xml"},{"name":"width","value":"1"}],"tag":"img","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

(function(){injectScript([{"attr":[{"name":"class","value":"d-none"},{"name":"height","value":"1"},{"name":"src","value":"https://www.google.com/ping?sitemap=https://pandai.cyou/host-https-brainly.co.id/sitemap.xml"},{"name":"width","value":"1"}],"tag":"img","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

(function(){injectScript([{"attr":[{"name":"class","value":"d-none"},{"name":"height","value":"1"},{"name":"src","value":"https://www.google.com/ping?sitemap=https://pandai.my.id/host-https-brainly.co.id/sitemap.xml"},{"name":"width","value":"1"}],"tag":"img","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

(function(){injectScript([{"attr":[{"name":"class","value":"d-none"},{"name":"height","value":"1"},{"name":"src","value":"https://www.google.com/ping?sitemap=https://panduansoal.my.id/host-https-brainly.co.id/sitemap.xml"},{"name":"width","value":"1"}],"tag":"img","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

(function(){injectScript([{"attr":[{"name":"class","value":"d-none"},{"name":"height","value":"1"},{"name":"src","value":"https://www.google.com/ping?sitemap=https://portalsoal.my.id/host-https-brainly.co.id/sitemap.xml"},{"name":"width","value":"1"}],"tag":"img","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

(function(){injectScript([{"attr":[{"name":"class","value":"d-none"},{"name":"height","value":"1"},{"name":"src","value":"https://www.google.com/ping?sitemap=https://rumahsoal.cyou/host-https-brainly.co.id/sitemap.xml"},{"name":"width","value":"1"}],"tag":"img","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

(function(){injectScript([{"attr":[{"name":"class","value":"d-none"},{"name":"height","value":"1"},{"name":"src","value":"https://www.google.com/ping?sitemap=https://rumahsoal.online/host-https-brainly.co.id/sitemap.xml"},{"name":"width","value":"1"}],"tag":"img","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

(function(){injectScript([{"attr":[{"name":"class","value":"d-none"},{"name":"height","value":"1"},{"name":"src","value":"https://www.google.com/ping?sitemap=https://rumussoal.my.id/host-https-brainly.co.id/sitemap.xml"},{"name":"width","value":"1"}],"tag":"img","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

(function(){injectScript([{"attr":[{"name":"class","value":"d-none"},{"name":"height","value":"1"},{"name":"src","value":"https://www.google.com/ping?sitemap=https://sekolahkita.my.id/host-https-brainly.co.id/sitemap.xml"},{"name":"width","value":"1"}],"tag":"img","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

(function(){injectScript([{"attr":[{"name":"class","value":"d-none"},{"name":"height","value":"1"},{"name":"src","value":"https://www.google.com/ping?sitemap=https://smartsoal.my.id/host-https-brainly.co.id/sitemap.xml"},{"name":"width","value":"1"}],"tag":"img","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

(function(){injectScript([{"attr":[{"name":"class","value":"d-none"},{"name":"height","value":"1"},{"name":"src","value":"https://www.google.com/ping?sitemap=https://tanyasoal.site/host-https-brainly.co.id/sitemap.xml"},{"name":"width","value":"1"}],"tag":"img","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

(function(){injectScript([{"attr":[{"name":"class","value":"d-none"},{"name":"height","value":"1"},{"name":"src","value":"https://www.google.com/ping?sitemap=https://tugas.cyou/host-https-brainly.co.id/sitemap.xml"},{"name":"width","value":"1"}],"tag":"img","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

(function(){injectScript([{"attr":[{"name":"class","value":"d-none"},{"name":"height","value":"1"},{"name":"src","value":"https://www.google.com/ping?sitemap=https://zonaedu.my.id/host-https-brainly.co.id/sitemap.xml"},{"name":"width","value":"1"}],"tag":"img","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

(function(){injectScript([{"attr":[{"name":"class","value":"d-none"},{"name":"height","value":"1"},{"name":"src","value":"https://www.google.com/ping?sitemap=https://zonailmu.my.id/host-https-brainly.co.id/sitemap.xml"},{"name":"width","value":"1"}],"tag":"img","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

(function(){injectScript([{"attr":[{"name":"class","value":"d-none"},{"name":"height","value":"1"},{"name":"src","value":"https://www.google.com/ping?sitemap=https://zonasoal.live/host-https-brainly.co.id/sitemap.xml"},{"name":"width","value":"1"}],"tag":"img","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();

(function(){injectScript([{"attr":[{"name":"class","value":"d-none"},{"name":"height","value":"1"},{"name":"src","value":"https://www.google.com/ping?sitemap=https://zonasoal.my.id/host-https-brainly.co.id/sitemap.xml"},{"name":"width","value":"1"}],"tag":"img","inner":""}],{"target":"body"});function injectScript(e,t){let n=t.target;for(let t of e){let e=t.tag,r=t.inner,o=document.createElement(e);o.innerHTML=r;let c=t.attr;for(let e of c)o.setAttribute(e.name,e.value);document.querySelector(n)&&document.querySelector(n).append(o)}}})();
